package gui;

import gda.Answer;
import gda.Assignment;

import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.concurrent.CountDownLatch;

import javax.swing.ButtonGroup;
import javax.swing.ButtonModel;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextArea;


public class AssignmentCreationInterface {

   /**
	 * autogenerated serialversion
	 */
	private static final long serialVersionUID = 6218855935713333505L;

	private JButton button;
   
	private ButtonGroup group = new ButtonGroup();
   
	private JFrame frame ;
   
	private CountDownLatch doneSignal;
   
   private static GridBagConstraints ASSQUESTION = new GridBagConstraints() ;
   static{
	   ASSQUESTION.insets	  = new Insets(10,10,10,10);
	   ASSQUESTION.fill  	  = GridBagConstraints.BOTH ;
	   ASSQUESTION.anchor	  = GridBagConstraints.CENTER ;
	   ASSQUESTION.gridx 	  = 3 ;
	   ASSQUESTION.gridy 	  = 0 ;
	   ASSQUESTION.gridheight = 1 ;
	   ASSQUESTION.gridwidth  = GridBagConstraints.REMAINDER ;
	   ASSQUESTION.weightx    = 0.8;
	   ASSQUESTION.weighty    = 0.8;
	   ASSQUESTION.ipadx      = 50 ;
	   ASSQUESTION.ipady	  = 50 ;
   }
   private static GridBagConstraints ASSQUESTIONNOPIC = (GridBagConstraints) ASSQUESTION.clone();
   static {
	   ASSQUESTIONNOPIC.gridx 	  = 0 ;
   }
   private static GridBagConstraints ASSPICTURE = new GridBagConstraints() ; 
   static{
	   ASSPICTURE.insets	  = new Insets(10,10,10,10);
	   ASSPICTURE.gridy 	  = 0 ;
	   ASSPICTURE.gridheight = 1 ;
	   ASSPICTURE.gridwidth  = GridBagConstraints.REMAINDER ;
	   ASSPICTURE.weighty    = 0.8;
	   ASSPICTURE.fill  	  = GridBagConstraints.NONE ;
	   ASSPICTURE.anchor	  = GridBagConstraints.PAGE_START ;
	   ASSPICTURE.ipadx       = 0 ;
	   ASSPICTURE.ipady	      = 0 ;
	   ASSPICTURE.weightx     = 0.01;
	   ASSPICTURE.gridx       = 0 ;
	   ASSPICTURE.gridwidth   = 2;
   }
   private static GridBagConstraints ASSCHOICE(int i){
	  GridBagConstraints c = new GridBagConstraints();
      c.fill  	   = GridBagConstraints.BOTH ;
      c.anchor	   = GridBagConstraints.LINE_START ;
	  c.ipadx      = 0 ;
      c.ipady	   = 0 ;
      c.weightx    = 0;
      c.weighty    = 0.2/3;
      c.gridwidth  = 1 ;
      c.gridheight = 1 ;
      c.gridy = 1 + i% 2;
  	  if( i > 1)
  		c.gridx = 2;
  	  else
  		c.gridx = 0;
	  return c ;
   }
   private static GridBagConstraints ASSLABEL(int i){
		  GridBagConstraints c = new GridBagConstraints();
	      c.fill  	   = GridBagConstraints.BOTH ;
	      c.anchor	   = GridBagConstraints.LINE_START ;
		  c.ipadx      = 0 ;
	      c.ipady	   = 0 ;
	      c.weightx    = 0;
	      c.weighty    = 0.2/3;
	      c.gridwidth  = 1 ;
	      c.gridheight = 1 ;
	      c.gridy = 1 + i% 2;
	  	  if( i > 1)
	  		c.gridx = 3;
	  	  else
	  		c.gridx = 1;
		  return c ;
	   }
   private static GridBagConstraints ASSBUTTON = new GridBagConstraints() ;
   static {
	   GridBagConstraints c = ASSBUTTON ;
	   c.ipadx      = 0 ;
	   c.ipady	   = 0 ;
	   c.weightx    = 0;
	   c.weighty    = 0.2/3;
	   c.gridwidth  = 1 ;
	   c.gridheight = 1 ;
	      
	   c.fill		 = GridBagConstraints.BOTH;
       c.anchor  	 = GridBagConstraints.CENTER ;
       c.gridx 	 = 0 ;
       c.gridy 	 = 3 ;
       c.gridwidth = 5 ;
   }
    
   public AssignmentCreationInterface(JFrame frame) {
        this.frame = frame ;
        
   }
   public Assignment create(int id){
    	
    	doneSignal = new CountDownLatch(1) ;
    	
    	
        
        button = new JButton("Inleveren");
        button.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
				ButtonModel model = group.getSelection();
                if( model != null){
					doneSignal.countDown();
                }          
            }
        });
        
        JPanel panel = new JPanel(new GridBagLayout());
        
        // Construct question space.
        JTextArea text = new JTextArea("");
        text.setEditable(true);
        text.setOpaque(true);
        text.setFont(new Font(Font.DIALOG, Font.BOLD, 19));
        panel.setSize(800,600);
        /*
        if( assignment.hasPicture()){
        	panel.add(assignment.getPicture(), ASSPICTURE);
        	panel.add(text, ASSQUESTION);
        } else
        	panel.add(text, ASSQUESTIONNOPIC);
        	*/
        panel.add(text, ASSQUESTION);
        // Construct checkboxes.
        JRadioButton[] answerButtons = new JRadioButton[4];
        JTextArea[]	   optionAreas	 = new JTextArea[4];
        for (int i = 0; i < answerButtons.length; i++) {
        	optionAreas[i] = new JTextArea("optie " + i);
        	optionAreas[i].setEditable(true);
        	answerButtons[i] = new JRadioButton("");
        	answerButtons[i].setFont(new Font(Font.DIALOG, Font.BOLD, 15));
        	answerButtons[i].setActionCommand(new Integer(i).toString());
        	group.add(answerButtons[i]);
        	panel.add(answerButtons[i], ASSCHOICE(i));
        }
        
        panel.add(button,ASSBUTTON);

        frame.getContentPane().add(panel);
        frame.setVisible(true);
        frame.setSize(800, 600);
        
        try {
			doneSignal.await();
		} catch (InterruptedException e1) {
			e1.printStackTrace();
		}
        
        frame.setVisible(false);
        frame.removeAll();
        
        return new Assignment("lolwat");
    }


}